In [199]:
import pandas as pd
import numpy as np
import seaborn as sns

In [200]:
import warnings
warnings.filterwarnings('ignore')

In [201]:
df = pd.read_csv('/content/mtcars.csv')

In [202]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [203]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [204]:
df.nunique()

model    32
mpg      25
cyl       3
disp     27
hp       22
drat     22
wt       29
qsec     30
vs        2
am        2
gear      3
carb      6
dtype: int64

In [205]:
df.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [206]:
x = df.drop(['mpg', 'model'], axis=1)
y = df['mpg']

In [207]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [208]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [209]:
model.score(x_train,y_train)

0.8750483703126839

In [210]:
model.score(x_test,y_test)

0.7466453084791007

LASSO MODEL

In [211]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
lasso = linear_model.Lasso(alpha=50, max_iter=100,tol=0.1)
lasso.fit(x_train, y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [212]:
df = pd.get_dummies(df ,drop_first=True)

In [213]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [214]:
lasso_reg.score(x_test,y_test)

0.6232192482702952

In [215]:
lasso_reg.score(x_train,y_train)

0.7472562013197046

RIDGE MODEL

In [216]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
Ridge = linear_model.Ridge(alpha=50, max_iter=100,tol=0.1)
Ridge.fit(x_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [217]:
Ridge.score(x_test,y_test)

0.745882637862139

In [218]:
Ridge.score(x_train,y_train)

0.7979855440770283

ELASTIC NET

In [219]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
elastic = linear_model.ElasticNet(alpha=50, max_iter=100,tol=0.1)
elastic.fit(x_train, y_train)

ElasticNet(alpha=50, max_iter=100, tol=0.1)

In [220]:
elastic.score(x_test,y_test)

0.625008118324095

In [221]:
elastic.score(x_train, y_train)

0.7524951373051341